language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
sudo: false
env:
  - DJANGO_VERSION=3.1
  - DJANGO_VERSION=3.2
before_install:
  - pip install httpretty mock coverage codecov
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
script:
  - python setup.py test
after_success:
  - codecov --env DJANGO_VERSION
